### ISSUE TITLE
CRUD read fails during decode if top node in yang module is a list

### ISSUE THREAD

**Issue by abhikeshav** [CiscoDevNet/ydk-gen#194]
For the [oc-pattern](https://github.com/CiscoDevNet/ydk-gen/blob/master/yang/ydktest/oc-pattern%402015-11-17.yang#L42) test yang model, the CRUD read on A() fails during decoding phase:

```
  File "ydk/services/crud_service.py", line 151, in read
    return provider.decode(payload, read_filter)
  File "ydk/providers/netconf_provider.py", line 87, in decode
    return self.sp_instance.decode(payload, read_filter)
  File "ydk/providers/_provider_plugin.py", line 132, in decode
    XmlDecoder._bind_to_object(payload, entity, self._get_capabilities())
  File "ydk/providers/_decoder.py", line 183, in _bind_to_object
    curr_rt = get_root(rt, entity._common_path, _yang_ns._namespaces)
  File "ydk/models/oc/oc_pattern.py", line 104, in _common_path
    raise YPYModelError('Key property a is None')
ydk.errors.YPYModelError: Key property a is None
```

Same issue with ``` codec_service.decode(provider,'''<A xmlns="http://cisco.com/ns/yang/oc-pattern">
  <a>Hello</a>
</A>''')```

**Comment by psykokwak4** [comment]
Currently the [`get_top_container_for_namespace`](https://github.com/CiscoDevNet/ydk-gen/blob/master/sdk/python/ydk/providers/_decoder.py#L44) in decoder and does not set YANG list key value, this will cause subsequent execution of _commen_path raise `YPYModelError`, might need to set list key value in `get_top_container_for_namespace` recursively.

**Comment by psykokwak4** [comment]
In this [generated API](https://github.com/CiscoDevNet/ydk-gen/blob/master/test/test-cases/python/expected/ydk/models/oc/oc_pattern.py#L50) for [oc-pattern](https://github.com/CiscoDevNet/ydk-gen/blob/master/yang/ydktest/oc-pattern%402015-11-17.yang#L48) test yang model, we have this leafref `A.a` assigned as None when initializing, is this expected behavior or a bug? Added sanity test for this but manually assign `A.b.b` to `A.a`.

**Comment by abhikeshav** [comment]
I think that is expected as we initialize integers to none. The recursively setting of keys should work. Thanks for looking into this.
