### ISSUE TITLE
parallel generation to reduce runtime

### ISSUE THREAD

**Issue by siming85** [CiscoDevNet/ydk-gen#212]
it takes 27 minutes on a server with 8G memory/4 x3.2Ghz cpu to generate the python bindings for IOSXE

since this currently runs generation one file after another - more processors/memory and processes would reduce this time drastically.

**Comment by abhikeshav** [comment]
On investigation, it appears that the generation was slow for the huge `ned.yang` file and has nothing to do with parallelization. It looks like the generation was slow because of YDK model tests which were also being generated by default. With commit e7d6c401344e892501486dbfad9497caa889384f, the generation of YDK model tests has been made optional. So, the generation time should be lot better
