### ISSUE TITLE
Circular import dependency

### ISSUE THREAD

**Issue by siming85** [CiscoDevNet/ydk-gen#216]
Error:

      File "test.py", line 7, in <module>
        from ydk.models.ietf_interfaces import Interfaces
      File "ydk/ydk-gen/gen-api/python/ydk/models/ietf_interfaces.py", line 40, in <module>
        from ydk.models.ietf_diffserv_classifier import FilterTypeIdentity
      File "ydk/ydk-gen/gen-api/python/ydk/models/ietf_diffserv_classifier.py", line 33, in <module>
        from ydk.models.policy_types import ClassTypeIdentity
      File "ydk/ydk-gen/gen-api/python/ydk/models/policy_types.py", line 19, in <module>
        from ydk.models.ietf_diffserv_classifier import FilterTypeIdentity
    ImportError: cannot import name FilterTypeIdentity

two modules both trying to import FilterTypeIdentity

this is generated off an ASR1k's models.

**Comment by siming85** [comment]
models used

[models.zip](https://github.com/CiscoDevNet/ydk-gen/files/412147/models.zip)

**Comment by abhikeshav** [comment]
This issue doesn't look easy to fix based on the set of models being used above. There is a complex circular dependency which means that even if only the module is imported or if absolute import of the module is used, there is still an issue with one of the dependent modules importing the current module, which causes an ```AttributeError```.

```
Traceback (most recent call last):
  File "ydk/tests/import_tests.py", line 12, in test_ietf_diffserv_action
    from ydk.models.ietf_diffserv_action import AlgorithmicDropIdentity
  File "ydk/models/ietf_diffserv_action.py", line 27, in <module>
    import ydk.models.ietf_diffserv_policy
  File "ydk/models/ietf_diffserv_policy.py", line 33, in <module>
    import ydk.models.ietf_diffserv_classifier
  File "ydk/models/ietf_diffserv_classifier.py", line 33, in <module>
    import ydk.models.policy_types
  File "ydk/models/policy_types.py", line 143, in <module>
    class InputInterfaceIdentity(ydk.models.ietf_diffserv_classifier.FilterTypeIdentity ,):
AttributeError: 'module' object has no attribute 'ietf_diffserv_classifier'
```

The easiest solution may be to remove the offending yang models from the profile being used to generate the APIs.

Let me know if anyone has any ideas about this.

**Comment by siming85** [comment]
the better question is why are these imported?

there seems to be quite a few circular imports in ietf_interfaces.py file, but none of the imports are actually used.

So.. if you do this:
```
#from ydk.models.ietf_diffserv_classifier import FilterTypeIdentity
#from ydk.models.policy_types import MetricEnum
#from ydk.models.policy_types import PolicyTypeIdentity
```

it imports.

**Comment by psykokwak4** [comment]
Hi Siming,

Those three classes are imported because they are supposed to be assigned to attributes, for example, the `FilterTypeIdentity` is supposed by used in:
- `InterfacesState.Interface.DiffservTargetEntry.DiffservTargetClassifierStatistics.QueuingStatistics.WredStats.SubclassLists.SubclassList.match_type`
- `InterfacesState.Interface.DiffservTargetEntry.DiffservTargetClassifierStatistics.MarkingStats.MarkingDscpTunnelStats.MarkingDscpTunnelCfg.SetValTablemap.to_type`

And some other places. 

I think you are correct, those attributes above are initialized as `None`, and we don't need to generate import statements for them. Removing those unnecessary import statements could resolve this issue.

However, we still need to preserve some import statements for `Identity`, for identity derived from identity in imported YANG models. And I think this use case will not introduce cyclic dependencies discovered in this issue.

Thanks,

Xiaoqin
