### ISSUE TITLE
Deviations should be handled in a separate bundle

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#237]
Deviations are currently not handled in a separate bundle.  Therefore, the cisco-ios-xr bundle has a hard dependency on the openconfig bundle.  An user should be able to install the cisco-ios-xr bundle w/o installing the openconfig bundle.  The latter should only be required if the user plans to use OpenConfig models with an IOS XR device.

**Comment by psykokwak4** [comment]
I think the deviation is not the reason for `cisco-ios-xr` bundle dependency on `openconfig` bundle. The dependency could be customized in profile file for [`cisco-ios-xr`](https://github.com/CiscoDevNet/ydk-gen/blob/master/profiles/bundles/cisco-ios-xr.json#L421)  and removed by removing json block starting from line 421, I added this only for demonstration purpose, sorry about this obscurity.

And for deviation, for current bundles like `cisco-ios-xr`, `openconfig` and `ietf`, we are not generating any deviation meta files like we have in [`ydktest`](https://github.com/CiscoDevNet/ydk-gen/blob/master/test/test-cases/python/expected/ydk/models/_deviate/_ydktest_sanity_deviations_types.py) package. I think bundle should work with deviation, because at runtime we use `MetaService` to import deviation meta data and inject `i_meta` to entity. Namespace package should not affect this workflow. Will update usecase with CI in the future.

**Comment by 111pontes** [comment]
Thanks for the clarification, it'd be great if you can remove the redundant dependency in the cisco-ios-xr bundle.

**Comment by 111pontes** [comment]
Thanks.  We should be able to close this issue once we have the test coverage.
