### ISSUE TITLE
Come up with scripts to do ydk-gen/ydk-py install in one shot

### ISSUE THREAD

**Issue by abhikeshav** [CiscoDevNet/ydk-gen#36]
Currently, there are a lot of steps which need to be manually carried out to install ydk-gen or ydk-py. There needs to be a simple bash script which takes care of everything (including installing dependencies and setting up environment). This will make it easy for users to install and use ydk-gen and/or ydk-py

**Comment by psykokwak4** [comment]
primitive install script checked in [here](https://github.com/psykokwak4/ydk-gen/blob/install/install.sh), let me know if it works/what you think

**Comment by abhikeshav** [comment]
Looks good overall. One comment on the commit

**Comment by einarnn** [comment]
Have we considered the steps required before we get to installing the ydk-py or ydk-gen? IOW, there are typically a number of packages that require to be installed on linux or OS X before we can successfully install the python components. Typically, we need (ubuntu package names, I think):

```
libxml2-dev
libxslt-dev
python-dev
zblib1g-dev
```

And there may be more. It would be good to have this information in a README (if it isn't already) and perhaps even have a script that can install these dependencies, at least on Linux for distros like RedHat/CentOS/Fedora/Ubuntu. Then, for extra credits, if we can incorporate options for Homebrew and MacPorts users as well, that'd be great! (And in most of our self-interests since I think most of us are Mac users;-)

**Comment by abhikeshav** [comment]
Agreed about a script which can install the pre-requisites before installing ydk-gen. The ydk-py README has more detailed information about the pre-requisites before installing. I will need to copy that info to ydk-gen README as well. This may also tie into issue #82, which will help in dealing with the actual installing of ydk-gen+dependencies.
