### ISSUE TITLE
Python script can't be interrupted while building model cache

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#434]
Python script hangs when interrupted (SIGINT/ctrl-c) while building the model catch.  No further models are downloaded from the server and the NETCONF session remains opened.

**Comment by psykokwak4** [comment]
I think it is a [fundamental flaw](https://docs.python.org/3.6/library/signal.html#execution-of-python-signal-handlers) in Python:

> A long-running calculation implemented purely in C (such as regular expression matching on a large body of text) may run uninterrupted for an arbitrary amount of time, regardless of any signals received. The Python signal handlers will be called when the calculation finishes.

Searched for workarounds and found one [here](http://snakesthatbite.blogspot.com/2010/09/cpython-threading-interrupting.html): 
```python
import time
import threading

from ydk.providers import NetconfServiceProvider

shutdown_event = threading.Event()

provider = None

def dowork():
    while not shutdown_event.is_set():
        global provider
        if provider is None:
            print("connetging...")
            provider = NetconfServiceProvider('127.0.0.1','admin','admin',1220)
            print("finished connetging...")

def main():
    """ Start some threads & stuff. """
    t = threading.Thread(target=dowork, args=(), name='worker')
    t.start()

    try:
        while t.is_alive():
            t.join(timeout=0.1)
    except (KeyboardInterrupt, SystemExit):
        shutdown_event.set()

if __name__ == '__main__':
    main()

```
I was able to use two ``KeyboardInterrupt`` to exit and the NETCONF session is closed.

**Comment by abhikeshav** [comment]
Interesting. Thanks for the input, Xiaoqin. Last time I tried python wrapper class for `NetconfServiceProvider` is that it has to be cast back into the original C++ object because [it is called in C++](https://github.com/CiscoDevNet/ydk-gen/blob/master/sdk/cpp/core/src/crud_service.cpp#L122).

**Comment by psykokwak4** [comment]
hmm.. what about adding helper class in python.cpp(`PyNetconfServiceProvider`) and wrapper class(`class NetconfServiceProvider(ydk_.providers.NetconfServiceProvider)`) in python code? something like current implementation for Entity(and also need to declare `get_root_schema`, `invoke`, `get_encoding` virtual)?

**Comment by abhikeshav** [comment]
Sure. Feel free to try it out

**Comment by psykokwak4** [comment]
Got a basic one working [here](https://github.com/psykokwak4/ydk-gen/blob/8590def1761b94b565a59836dc312395f28cd8af/sdk/python/core/test_nc.py)(only for `KeyboardInterrupt`, need to reinsall libydk and Python core library). I need more than one `KeyboardInterrupt`(mostly two) to exit, not sure why

**Comment by 111pontes** [comment]
Definitely worth investigating in more detail.

**Comment by psykokwak4** [comment]
For the daemon thread workaround, we could put the long running C backend(module downloading) to a daemon thread, capture signals in main thread then kill Python interpreter as well as long running C backend(a basic one working here https://git.io/v9HrW). However this might introduce trouble if YDK is being used in complex scenarios, since we are handling threading implicitly(and will also deprive the user of this right).
To solve this issue, the user could always create context managers that could put long running C backend to a daemon thread.

Shall we continue this approach or leave the right to the user?

---
Backgrounds:
[GIL](http://www.dabeaz.com/GIL/)
[only the main thread of a process will receive signals](https://pymotw.com/3/signal/index.html#signals-and-threads)
[the entire Python program exits when only daemon threads are left](https://docs.python.org/2/library/threading.html#thread-objects)

**Comment by abhikeshav** [comment]
I think we could leave this up to the user to handle since we do not want to introduce the kind of "hidden" behavior of running our provider in a daemon thread

**Comment by abhikeshav** [comment]
Since we now optimized the model download/caching this issue should not matter, but feel free to reopen if it shows up again
