### ISSUE TITLE
_has_data method logic is broken?

### ISSUE THREAD

**Issue by emjemj** [CiscoDevNet/ydk-gen#487]
I generated model bindings for a custom yang model and as I was looking into how to validate that all data has been filled in correctly, I found the _has_data model. When I hadn't filled in all data correctly it was still returning true, which shouldn't happen.

The generated module looks like this
``` python
 
def _has_data(self):
        if self.address is not None and self.address._has_data():
            return True

        if self.igp is not None and self.igp._has_data():
            return True

        if self.interfaces is not None:
            for child_ref in self.interfaces:
                if child_ref._has_data():
                    return True

        if self.remote_device is not None:
            return True

        if self.remote_interface is not None:
            return True

        if self.service_id is not None:
            return True

        return False
```
This returns true if any leaf or container has data and only returns False if no information has been added at all. Is this per design or simply something that nobody is using? Is there another way to validate data added to the model which I don't know about? 

My feeling is that the method should look something like this
``` python
  def _has_data(self):
        if self.address is None or not self.address._has_data():
            return False

        if self.igp is None or not self.igp._has_data():
            return False

        if self.interfaces is not None:
            for child_ref in self.interfaces:
                if not child_ref._has_data():
                    return False
        else:
            return False

        if self.remote_device is None:
            return False

        if self.remote_interface is None:
            return False

        if self.service_id is None:
            return False

        return True
```
This would cause _has_data to only return True if all leafs has data.

**Comment by psykokwak4** [comment]
> Is this per design or simply something that nobody is using?

`_has_data` is used in current implementation of [encoder](https://github.com/CiscoDevNet/ydk-gen/blob/0b249c901622522c98025da234c022df84abd401/sdk/python/core/ydk/providers/_encoder.py), [validator](https://github.com/CiscoDevNet/ydk-gen/blob/209522c0a35681c6307a0e4a999d7a468e64ce41/sdk/python/core/ydk/providers/_validator.py) and [crud_service](https://github.com/CiscoDevNet/ydk-gen/blob/e20c6cb65680079371cc98cc6f52406c10455988/sdk/python/core/ydk/services/crud_service.py). It is by design in my opinion. For example in the current implementation of [crud_service](https://github.com/CiscoDevNet/ydk-gen/blob/e20c6cb65680079371cc98cc6f52406c10455988/sdk/python/core/ydk/services/crud_service.py#L196), line 196 checks if any field is populated, and raise error if non is found(no data found in device side).

> Is there another way to validate data added to the model which I don't know about?

Validation for data added to the model happens in every encoding.

> I was looking into how to validate that all data has been filled in correctly

As far as I know, monkey patching errors(assign a string to an expected boolean attribute), and integer range errors(as defined in YANG constraints) are validated locally.

**Comment by emjemj** [comment]
I tried adding data which was incorrect, didn't match pattern requirements or whatever. When I then encoded this to xml, the fields were simply missing in the output, no errors were thrown.

Is there a defacto way to verify that a model does have all required data? Ideally something like this would be great.

``` yang
module mymodel {
    container something {
      leaf something-else {
          type string {
              pattern "(foo|bar)";
          }
          mandatory true;
    }
}
```

``` python
p = mymodel.Something()

try:
  p.validate()
except:
  print("Data doesn't match model")
```
Or is there another way to make this happen? I would like to verify the data against the yang model with all checks, including must, patterns and data types.

**Comment by psykokwak4** [comment]
Validation against string pattern is currently [not supported](https://github.com/CiscoDevNet/ydk-gen/blob/master/sdk/python/core/ydk/providers/_validator.py#L158) because regex pattern used in Python follows different standard compared to regex used in [YANG](https://www.w3.org/TR/2004/REC-xmlschema-2-20041028/#regexs).
Full-blown validation service is supposed be added in new infra, and feel few to contribute to the current implementation.
However the below behavior seems wired:
> When I then encoded this to xml, the fields were simply missing in the output

Could you enable logging or provide YANG models/test scripts used so that we could reproduce/confirm this issue?

**Comment by abhikeshav** [comment]
Currently, to validate the data, you need to either use the `codec` or `crud` service. In the next release of ydk, `validation` service is going to be supported.

`_has_data` is only meant to check if the object has any data.
