### ISSUE TITLE
C++ YList: there is no function to remove elements from the list

### ISSUE THREAD

**Issue by vhuertas** [CiscoDevNet/ydk-gen#811]
Hi,

I am writing a C++ program with the ydk in C++ and I have seen that for ydk::YList there is the "append" function but not "remove". Is there some workaround in order to remove elements from the list?

Thanks for your attention!

Regards,

**Comment by ygorelik** [comment]
The remove/delete function was not included to the ydk::YList class intentionally, because the operation will break order of entities in the list. Originally the feature was designed just to get key access to the YList data obtained from device. This implies that delete operation is irrelevant. Apparently you have another use case, which currently is not covered by YDK.
As a workaround I would suggest to build new YList and include to it all the elements that you need.

**Comment by ygorelik** [comment]
I do not understand, what are you trying to accomplish. The YDK already gives you all C++ classes for the Yang model. Could you please elaborate on your specific use case. 
Unfortunately neither of the described methods are good. The issue is that all members of the YList also included into the parent node children map. That map is based on underlying _libyang_ node structures, which are not accessible from YDK API. So any removal or even replacement of a child in the YList is going to break the children map in the parent. That is unacceptable.
The workaround that I mentioned would be build **new top level entity** "from top to bottom" and on the way of building the data tree exclude unwanted element.

**Comment by ygorelik** [comment]
We have decided to add this functionality to the YList class. We will update you when it is ready for download.

**Comment by vhuertas** [comment]
Thanks a lot!
Kind regards,

**Comment by vhuertas** [comment]
Just one further question,

Having a look at the CiscoDevNet/ydk-gen git repository I didn't see such update of the code for YList. Instead They have been added to the fork from ygorelik. When the issues are published here, are some of them solved in the in ygorelik fork and some in the CiscoDevNet? Or will they be  applied to both repositories? is the #811 issue only solved in one of the two repos? It's a bit confusing...

I am using the ydk-cpp directly as the ietf bundle is the one I am interested in.  But will this code update be integrated in  ydk-ccp as well?

If I have to git clone the ygorelik repository I will but I just want to have a clear picture about both ygorelink and CiscoDevNet branches (and its differences) and if all will be merged someday,

Thanks in advance,
