### ISSUE TITLE
YFilter merge/replace needs to support new values

### ISSUE THREAD

**Issue by abhikeshav** [CiscoDevNet/ydk-gen#884]
Currently, `YFilter.merge` or `YFilter.replace` can only be set to leafs. But the use case for replace or merge operation is to provide a new value to be set. Something like the below could be supported:

```python
from ydk.models.cisco_ios_xr import Cisco_IOS_XR_cdp_cfg
from ydk.filters import YFilter

# First create the top-level Cdp() object
cdp = Cisco_IOS_XR_cdp_cfg.Cdp()

# Assign YFilter.replace to the 'timer' leaf with new value 5 to replace old value
cdp.timer = YFilter.replace(5)

# Call the CRUD update on the top-level cdp object
# (assuming you have already instantiated the service and provider)
result = crud.update(provider, cdp)
```

**Comment by ygorelik** [comment]
Implementation of the enhancement in YDK-0.8.4 is too complex due to underlying C++ code and would require changes in generated code, which does not seem reasonable. Instead of that feature it is suggest implement workaround, which is currently working with no code changes. The assignment of value and filter to the leaf, should look like this:
 
**Original 0.5.5 code:**
 ```
entity.leaf = REPLACE(5)
 ```
**Implementation in 0.8.3:**
``` 
entity.leaf = 5
entity.set_filter(‘leaf’, YFilter.replace)
 ```
Here, the _set_filter()_ method of an Entity class expects two parameters: _leaf name_ and _yfilter_.
