### ISSUE TITLE
No way to retrieve numeric value of enums in cpp generated code

### ISSUE THREAD

**Issue by georgeyanev** [CiscoDevNet/ydk-gen#944]
## Expected Behavior
I expect to be able to retrieve the numeric value of an enum in cpp generated code.

## Current Behavior
This seems not possible.

## Steps to Reproduce
This yang is passed in a bundle to the generator:
```
module enum-test {
  namespace "ns0:ns0";
  prefix "ns0";

  typedef loglevel-type {
    type enumeration {
      enum "INFO" {
        value 7;
      }
      enum "DEBUG" {
        value 8;
      }
    }
  }

  container main {
    leaf name {
     type string;
    }

    leaf loglevel {
      type loglevel-type;
    }
  }
}
```
This is an excerpt of the cpp generated code for the yang above:
```
class Main : public ydk::Entity
{
    public:
       /*
        Not interesting part is removed
       */

        ydk::YLeaf name; //type: string
        ydk::YLeaf loglevel; //type: LoglevelType   // Isn't this supposed to be of type LoglevelType?
}; // Main

class LoglevelType : public ydk::Enum
{
    public:
        static const ydk::Enum::YLeaf INFO;
        static const ydk::Enum::YLeaf DEBUG;
};
```
The loglevel field of the main class is of type ydk:YLeaf where the numeric value is not present.
Is there a way to retrieve it?

## System Information
YDK-0.8.4
Ubuntu 18.04.2 LTS on a x86_64 machine

**Comment by ygorelik** [comment]
Added _enum_value_ member to _YLeaf_ class, which carries int value of the enum member. Expended unit tests for access/check of int value of enum leaf.

**Comment by ygorelik** [comment]
Failed to get enum_value when reading enumeration data from device.

**Comment by ygorelik** [comment]
Developed partial solution for the issue by providing a static function inside generated _ydk::Enum_ inherited class, which translates _enum_ name to _enum_value_. Here how it looks like in the bundle code:
```
class LoglevelType : public ydk::Enum
{
    public:
        static const ydk::Enum::YLeaf INFO;
        static const ydk::Enum::YLeaf DEBUG;

        static int get_enum_value(const std::string name) {
            if (name == "INFO") return 7;
            if (name == "DEBUG") return 8;
            return -1;
        }
};
```
It would be complete, if the _set_value()_ generated function would set the leaf _enum_value_ automatically. Unfortunately I could not figure out how to do that for the common use, because the enum class could be declared in another C++ file and have different namespace. In current implementation the user should add one line of code to get/set _enum_value_ in a leaf, like this:
```
  std::cout << "Main LogLevel value: " << sReadPtr->loglevel.value << std::endl;
  sReadPtr->loglevel.enum_value = LoglevelType::get_enum_value(sReadPtr->loglevel.value);
  std::cout << "Main LogLevel enum_value: " << sReadPtr->loglevel.enum_value << std::endl;
```
